"""Generate ``tests/fixtures/recall_memories.jsonl`` from the local bagger DB.

This is a *local* dev tool — it reads ``~/.bagger/bagger.db`` and snapshots the
memory records that the golden set references (by ``expect_hashes``) plus a
sample of unrelated distractors, so the CI eval has a fixed, portable corpus
to search against.

Why a fixture at all? ``expect_hashes`` makes the *golden file* portable, but
CI still has no ``memory_records`` whose hashes match. This file closes that
gap: CI builds a temp DB from it, reindexes FTS and fake-embedder vectors, then
runs the same eval. Checks are portable; data is not (it lives here).

Run::

    python scripts/gen_recall_fixture.py            # 60 distractors
    python scripts/gen_recall_fixture.py 80         # custom distractor count

Do NOT commit your full ~/.bagger/bagger.db — this exports only the curated
relevant records + a bounded distractor sample.
"""

from __future__ import annotations

import json
import os
import random
import sqlite3
import sys
from pathlib import Path

DB = Path(os.path.expanduser("~/.bagger/bagger.db"))
GOLDEN = Path(__file__).resolve().parent.parent / "tests" / "fixtures" / "recall_golden.jsonl"
OUT = Path(__file__).resolve().parent.parent / "tests" / "fixtures" / "recall_memories.jsonl"

CONN = sqlite3.connect(str(DB))
CONN.row_factory = sqlite3.Row


def load_golden_hashes() -> set[str]:
    hashes: set[str] = set()
    for line in GOLDEN.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        for h in json.loads(line).get("expect_hashes", []):
            hashes.add(str(h))
    return hashes


def main() -> None:
    distractor_n = int(sys.argv[1]) if len(sys.argv) > 1 else 60
    relevant_hashes = load_golden_hashes()
    print(f"golden references {len(relevant_hashes)} distinct content hashes")

    placeholders = ",".join("?" * len(relevant_hashes))
    relevant_rows = CONN.execute(
        f"""
        SELECT id, type, content, topics, confidence, source, session_id, created_at, content_hash
        FROM memory_records
        WHERE content_hash IN ({placeholders})
        """,
        tuple(relevant_hashes),
    ).fetchall()
    print(f"found {len(relevant_rows)} relevant records in local DB")

    rel_hashes = {r["content_hash"] for r in relevant_rows}
    missing = relevant_hashes - rel_hashes
    if missing:
        print(f"WARNING: {len(missing)} golden hashes NOT found in local DB:", file=sys.stderr)
        for h in sorted(missing)[:10]:
            print(f"  {h}", file=sys.stderr)

    # Distractors: unrelated records (not in the relevant set), deduped by hash.
    # Random sampling gives the eval realistic lexical noise without leaking the
    # whole personal database.
    cand = CONN.execute(
        f"""
        SELECT id, type, content, topics, confidence, source, session_id, created_at, content_hash
        FROM memory_records
        WHERE content_hash NOT IN ({placeholders}) AND archived = 0
        """,
        tuple(relevant_hashes),
    ).fetchall()
    rng = random.Random(20260825)  # deterministic sample
    rng.shuffle(cand)
    distractors = []
    seen = set(rel_hashes)
    for r in cand:
        if r["content_hash"] in seen:
            continue
        seen.add(r["content_hash"])
        distractors.append(r)
        if len(distractors) >= distractor_n:
            break
    print(f"selected {len(distractors)} distractors")

    def to_line(r: sqlite3.Row, kind: str) -> dict:
        return {
            "key": f"{kind}-{r['content_hash'][:12]}",
            "type": r["type"],
            "content": r["content"],
            "topics": r["topics"] or "",
            "confidence": r["confidence"],
            "source": r["source"] or "claude",
            "session_id": r["session_id"] or "recall-fixture",
            "created_at": r["created_at"] or "2026-01-01T00:00:00+00:00",
            "content_hash": r["content_hash"],
        }

    lines = []
    for r in relevant_rows:
        lines.append(to_line(r, "rel"))
    for r in distractors:
        lines.append(to_line(r, "dist"))
    # stable order: by key
    lines.sort(key=lambda d: d["key"])

    header = [
        "# Memory corpus for the CI recall eval (consumed by scripts/eval_recall.py --ci).",
        "# Generated by scripts/gen_recall_fixture.py from ~/.bagger/bagger.db.",
        "# 'rel-' = records referenced by recall_golden.jsonl; 'dist-' = unrelated noise.",
        "# content_hash is sha256(content); the same value is what golden expect_hashes use.",
        "",
    ]
    with OUT.open("w", encoding="utf-8") as f:
        f.write("\n".join(header))
        for d in lines:
            f.write(json.dumps(d, ensure_ascii=False) + "\n")

    print(f"wrote {len(lines)} records -> {OUT}")


if __name__ == "__main__":
    main()
